spring:

  ## 指定运行配置文件
  profiles:
    active: dev

  ## druid pool setting
  datasource:
    druid:
      initial-size: 5
      max-active: 10
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      validation-query: select 1
      validation-query-timeout: 30000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      async-close-connection-enable: true

  ## mongo pool setting
  data:
    mongodb:
      min-connections-per-host: 1
      max-connections-per-host: 8
      threads-allowed-to-block-for-connection-multiplier: 5
      server-selection-timeout: 30000
      max-wait-time: 120000
      max-connection-idel-time: 0
      max-connection-life-time: 0
      connect-timeout: 10000
      socket-timeout: 0
      socket-keep-alive: false
      ssl-enabled: false
      ssl-invalid-host-name-allowed: false
      always-use-m-beans: false
      heartbeat-socket-timeout: 20000
      heartbeat-connect-timeout: 20000
      min-heartbeat-frequency: 500
      heartbeat-frequency: 10000

## 块游标
blockSignFile:
  path: ./sign/
  fileName: blockSign.txt

## 时间戳格式化类型
formatDate:
  formatUTC: "yyyy-MM-dd'T'HH:mm:ss'Z'"
  formatCST: "yyyy-MM-dd HH:mm:ss"