## 运行端口
server:
  port: 8089

spring:

  datasource:

    ## mysql
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://106.14.200.2:3307/gikeeData?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
      username: gikee
      password: gikee_data_service

  data:

    ## mongo
    mongodb:
      address: 47.100.15.84:27018
      database: test

    ## elasticsearch
    elasticsearch:
      cluster-name: gikee-cluster
      cluster-nodes: 47.103.77.104:9021,47.103.77.104:9022,47.103.77.104:9023
      poolSize: 20

  ## Redis config
  redis:
    host: 192.168.0.168
    port: 6379
    password:
    database: 0
    timeout: 20000
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1

## ethereum config
ethereum:
  #rpcUrl: http://blockChain:30301
  rpcUrl: http://192.168.0.168:30301

## websokct
websocket:
  url: ws://192.168.1.113:60080/bigChange/eth